version: '3.8'

services:
  postgres-users:
    image: postgres:16
    container_name: postgres-users
    environment:
      POSTGRES_USER: kainbear
      POSTGRES_PASSWORD: sups4
      POSTGRES_DB: users
    volumes:
      - postgres-users-data:/var/lib/postgresql/data
    ports:
      - "5434:5432" # Использование порта 5434

  web:
    build: .
    container_name: user-service
    command: uvicorn main:app --host 0.0.0.0 --port 8003 --reload
    ports:
      - "8003:8003"
    depends_on:
      - postgres-users

volumes:
  postgres-users-data: